# Generated by Django 5.0.6 on 2026-09-26 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('phone', 'Phone'), ('laptop', 'Laptop'), ('audio', 'Audio'), ('watch', 'Watch'), ('gaming', 'Gaming'), ('accessory', 'Accessory')], default='accessory', max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('brand', models.CharField(max_length=60)),
                ('tagline', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price, shown crossed out when the product is on sale.', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('specs', models.JSONField(blank=True, default=dict, help_text='e.g. {"Battery": "20 hours"}')),
                ('color', models.CharField(default='#1f2937', help_text='Hex colour for the product artwork.', max_length=7)),
                ('image_url', models.URLField(blank=True, help_text='Optional photo. Artwork is drawn when empty.')),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-featured', 'name'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='store_produ_is_acti_53e3fd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 0)), name='product_price_positive'),
        ),
    ]
